# For more information: https://laravel.com/docs/sail
version: '3'

services:
    nginx:
        image: nginx:alpine
        # container_name: nginx
        # restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            # - "7003:80"
            # - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/general/nginx-defail.conf:/etc/nginx/conf.d/default.conf:ro
            # - ./nginx/ssl/:/etc/nginx/ssl/
        # valumes:
        #   - ./docker/general/nginx-defail.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db
            - app
        links:
            - php
            - app
        networks:
            - scrapdatanetwork
        command: [nginx-debug, '-g', 'daemon off;']

    db:
        image: mysql:5.7
        # container_name: db
        # restart: unless-stopped
        tty: true
        ports:
          - "7306:3306"
        volumes:
          - mysqldata:/var/lib/mysql
        environment:
            # MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'scraperu'
            MYSQL_USER: 'scraperu'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
          - scrapdatanetwork

    php:
        image: php:7.4-fpm
        volumes:
          - ./:/var/www/html
        networks:
          - scrapdatanetwork
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: webapplaravel
        # container_name: app
        working_dir: /var/www/html
        volumes:
          - ./:/var/www/html
        ports:
          - "9000:9000"
        networks:
          - scrapdatanetwork

networks:
    scrapdatanetwork:
        driver: bridge
volumes:
    mysqldata:
        driver: local

# #  webapplaravel php:7.4-fpm mysql:5.7 nginx:alpine
